name: "Greeting Action"

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List action directory
        run: ls -la .github/actions/javascript-actions
  
      - name: Run greeting script
        uses: ./.github/actions/javascript-actions
        with:
          name: World
